### ISSUE TITLE
Error when running `local-log.js` example.

### ISSUE THREAD

**Issue by initbar** [algernon/potential-happiness#2]
### Environment:
* Ubuntu x64 (`Linux 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`)

### Error Reproduction:
1. `git clone <repo>`
2. `rpm install`
3. `ln -s /usr/bin/nodejs /usr/bin/node`
2. `./dashboard.js ../examples/local-log.js`

### Log:
```
user@user:/tmp/potential-happiness$ src/dashboard.js examples/local-log.js 
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by initbar** [comment]
Flushed out iptables rules, in case the connection was rejected due to restrictive policies - but, even with `INPUT`, and `OUTPUT` set to `ACCEPT`, I still see the same error. I'll setup a clean linux installation and try with different flavors later.

**Comment by kangman** [comment]
Same here
#Environment
```
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
```
#Log
```
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by algernon** [comment]
Not written in the README (yet), but you need Riemann running with `(ws-server {:host "127.0.0.1"})`, because potential-happines tries to subscribe to events via websockets. Similarly, it also wants ElasticSearch running too, but that doesn't need extra configuration (and fails more gracefully, I think).

**Comment by algernon** [comment]
Current master now has slightly better error reporting (writes to `ph.local-log.log`). You'll still need the Riemann & ElasticSearch stuff set up, but at least the program will not crash, but log an error instead.

**Comment by algernon** [comment]
I think that with the updates to README.md, and better error reporting, this can be closed. Please reopen if you disagree.
